# Generated by Django 2.0 on 2018-07-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180711_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('custom_can_add_user', 'Custom Can add User'), ('custom_can_edit_user', 'Custom Can edit User'), ('custom_can_delete_user', 'Custom Can delete User')), 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
    ]
