# Generated by Django 2.0 on 2018-07-08 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        ('refugee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.Food')),
                ('refugee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='refugee.Refugee')),
            ],
        ),
    ]
