# Generated by Django 2.0 on 2018-07-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
