# Generated by Django 2.0 on 2018-07-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_auto_20180711_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='picking_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
