# Generated by Django 2.0 on 2018-07-08 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Gender Name')),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Gender',
            },
        ),
        migrations.CreateModel(
            name='Refugee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Refugee Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('telephone', models.IntegerField(verbose_name='Telephone Number')),
                ('address', models.TextField(verbose_name='Physical Address')),
                ('date_time_registered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of Registration')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='refugee.Gender', verbose_name='Gender')),
            ],
            options={
                'verbose_name': 'Refugee',
                'verbose_name_plural': 'Refugees',
            },
        ),
    ]
