# Generated by Django 2.0 on 2018-07-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugee',
            name='telephone',
            field=models.BigIntegerField(verbose_name='Telephone Number'),
        ),
    ]
