# Generated by Django 2.0 on 2018-07-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refugee', '0003_auto_20180711_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ('name',), 'permissions': (('custom_can_add_gender', 'Custom Can add Gender'), ('custom_can_update_gender', 'Custom Can update Gender'), ('custom_can_delete_gender', 'Custom Can delete Gender')), 'verbose_name': 'Gender', 'verbose_name_plural': 'Gender'},
        ),
        migrations.AlterModelOptions(
            name='refugee',
            options={'ordering': ('date_time_registered', 'name'), 'permissions': (('custom_can_add_refugee', 'Custom Can add Refugee'), ('custom_can_update_refugee', 'Custom Can update Refugee'), ('custom_can_delete_refugee', 'Custom Can delete Refugee')), 'verbose_name': 'Refugee', 'verbose_name_plural': 'Refugees'},
        ),
    ]
