# Generated by Django 2.0 on 2018-07-08 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Unit Name')),
                ('abbreviation', models.CharField(max_length=5, verbose_name='Abbreviation')),
                ('description', models.TextField(verbose_name='Unit Description')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Food Name')),
                ('description', models.TextField(verbose_name='Food Description')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity_available')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.DistributionUnit', verbose_name='Distribution Units')),
            ],
        ),
    ]
