# Generated by Django 2.0 on 2018-07-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributionunit',
            options={'ordering': ('name',), 'verbose_name': 'Distribution Unit', 'verbose_name_plural': 'Distribution Units'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('name',), 'verbose_name': 'Food', 'verbose_name_plural': 'Food'},
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(verbose_name='Food Description or Remarks'),
        ),
    ]
