# Generated by Django 2.0 on 2018-07-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20180711_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributionunit',
            options={'ordering': ('name',), 'permissions': (('custom_can_add_food_unit', 'Custom Can add Food Unit'), ('custom_can_delete_food_unit', 'Custom Can delete Food Unit'), ('custom_can_update_food_unit', 'Custom can update Food Unit')), 'verbose_name': 'Distribution Unit', 'verbose_name_plural': 'Distribution Units'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('name',), 'permissions': (('custom_can_add_food', 'Custom Can add Food'), ('custom_can_delete_food', 'Custom Can delete Food'), ('custom_can_update_food', 'Custom can update Food')), 'verbose_name': 'Food', 'verbose_name_plural': 'Food'},
        ),
    ]
